title: "Guilherme R Barbosa - Data Analytics & Data Engineering"
description: "Dashboards, Codes, Pipelines and Learning"
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Guilherme R Barbosa"
github_username: "grbarbosa3"
exclude:
  - "README.md"
