title: "Guilherme R Barbosa - Data Analytics & Data Engineering"
description: "Projects, Codes, Builds and Learning"
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Guilherme R Barbosa"
github_username: "grbarbosa3"
youtube_channel: "@dataslinger6379"
medium_username: "dataslinger"
exclude:
  - "README.md"
